name: Python package tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Python ${{ matrix.python-version }} | xrpl-py ${{ matrix.xrpl-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
        xrpl-version: [2.5.0, 3.0.0, 4.0.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (xrpl-py ${{ matrix.xrpl-version }})
        run: |
          python -m pip install --upgrade pip
          pip install ".[testing]"
          pip install xrpl-py==${{ matrix.xrpl-version }}

      - name: Run unit tests (xrpl-py ${{ matrix.xrpl-version }})
        run: pytest --ignore=tests/test_integration.py

      - name: Run integration tests (xrpl-py ${{ matrix.xrpl-version }})
        env:
          XRPL_TESTNET_SECRET: ${{ secrets.XRPL_TESTNET_SECRET }}
          SEPOLIA_TESTNET_SECRET: ${{ secrets.SEPOLIA_TESTNET_SECRET }}
          PYTHONPATH: ${{ github.workspace }}/src
        run: pytest tests/test_integration.py

      - name: Run mypy
        run: mypy src/dhali
